import { useState } from 'react'
import { T, CG, GG, CT, fmt, todayStr, dleft, uid } from './lib/tokens.js'
import { aiCall, gmailCall } from './lib/ai.js'

// Shared UI
const Card = ({children,style,glow}) => <div style={{background:T.card,border:'1px solid '+T.border,borderRadius:14,padding:24,...(glow?{boxShadow:'0 0 30px rgba(200,200,255,.04)'}:{}),...style}}>{children}</div>
const Pill = ({children,color=T.silver,style}) => <span style={{background:color+'18',color,border:'1px solid '+color+'30',borderRadius:20,padding:'3px 12px',fontSize:11,fontWeight:600,letterSpacing:.5,whiteSpace:'nowrap',...style}}>{children}</span>
const Btn = ({children,onClick,v='p',style,disabled,icon}) => {
  const base = {display:'inline-flex',alignItems:'center',gap:6,padding:'9px 18px',borderRadius:10,border:'none',cursor:disabled?'not-allowed':'pointer',fontSize:13,fontWeight:600,transition:'all .15s',opacity:disabled?.45:1,...style}
  const vs = {p:{background:CG,color:'#080810',boxShadow:'0 2px 12px rgba(200,200,255,.15)'},g:{background:'transparent',color:T.silver,border:'1px solid '+T.border2},gold:{background:GG,color:'#1a0e00'},success:{background:'#0a2a1a',color:T.green,border:'1px solid #1a5a3a'},danger:{background:'#3a1010',color:T.red,border:'1px solid #5a2020'},glass:{background:'rgba(255,255,255,.04)',color:T.silver,border:'1px solid rgba(255,255,255,.08)'}}
  return <button style={{...base,...vs[v]}} onClick={onClick} disabled={disabled}>{icon && <span>{icon}</span>}{children}</button>
}
const Inp = ({val,onChange,ph,type='text',style,icon}) => <div style={{position:'relative',...style}}>{icon && <span style={{position:'absolute',left:12,top:'50%',transform:'translateY(-50%)',color:T.s2,fontSize:13,pointerEvents:'none'}}>{icon}</span>}<input type={type} value={val} onChange={e=>onChange(e.target.value)} placeholder={ph} style={{background:'rgba(255,255,255,.04)',border:'1px solid '+T.border2,borderRadius:10,padding:icon?'9px 12px 9px 36px':'9px 14px',color:T.text,fontSize:13,width:'100%',outline:'none',fontFamily:'inherit'}}/></div>
const Sel = ({val,onChange,opts,style}) => <select value={val} onChange={e=>onChange(e.target.value)} style={{background:T.card,border:'1px solid '+T.border2,borderRadius:10,padding:'9px 14px',color:T.text,fontSize:13,outline:'none',cursor:'pointer',...style}}>{opts.map(o=><option key={o.v} value={o.v}>{o.l}</option>)}</select>
const StatCard = ({label,value,sub,color=T.silver,icon,style}) => <div style={{background:T.card,border:'1px solid '+T.border,borderRadius:14,padding:'18px 20px',position:'relative',overflow:'hidden',...style}}><div style={{position:'absolute',top:0,left:0,right:0,height:2,background:color,opacity:.6}}/><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:10}}><span style={{fontSize:11,color:T.muted,fontWeight:600,letterSpacing:1,textTransform:'uppercase'}}>{label}</span>{icon && <span style={{fontSize:18,opacity:.5}}>{icon}</span>}</div><div style={{fontSize:26,fontWeight:800,color,letterSpacing:-.5,lineHeight:1}}>{value}</div>{sub && <div style={{fontSize:11,color:T.s2,marginTop:6}}>{sub}</div>}</div>
const TopBar = ({title,sub,actions}) => <div style={{background:'rgba(8,8,16,.95)',borderBottom:'1px solid '+T.border,padding:'16px 32px',display:'flex',alignItems:'center',justifyContent:'space-between',position:'sticky',top:0,zIndex:50}}><div><h1 style={{fontSize:20,fontWeight:700,color:T.text,letterSpacing:-.4}}>{title}</h1>{sub && <p style={{fontSize:12,color:T.s2,marginTop:2}}>{sub}</p>}</div><div style={{display:'flex',gap:10,alignItems:'center'}}>{actions}</div></div>
const Divider = () => <div style={{height:1,background:'linear-gradient(90deg,transparent,'+T.border2+',transparent)',margin:'16px 0'}}/>
const AIBlock = ({text,color=T.gold,label='AI Analysis'}) => text ? <div style={{background:'linear-gradient(135deg,'+color+'12,'+color+'06)',border:'1px solid '+color+'30',borderRadius:14,padding:18}}><div style={{fontSize:11,color,fontWeight:700,letterSpacing:1,textTransform:'uppercase',marginBottom:8}}>✦ {label}</div><p style={{fontSize:13,color:T.s3,lineHeight:1.7}}>{text}</p></div> : null

const NAV = [{id:'home',label:'Overview',icon:'⬡',desc:'Dashboard'},{id:'events',label:'Events',icon:'📅',desc:'Company Calendar'},{id:'shifts',label:'Shifts',icon:'⏱',desc:'Officer Scheduling'},{id:'roster',label:'Roster',icon:'◈',desc:'Personnel'},{id:'invoices',label:'Invoices',icon:'◧',desc:'Billing & Gmail'},{id:'leads',label:'Leads',icon:'◎',desc:'Pipeline'},{id:'linkedin',label:'LinkedIn',icon:'◉',desc:'Content'},{id:'payroll',label:'Payroll',icon:'◫',desc:'Paychex'}]

function Sidebar({active,setActive,alerts}) {
  return <div style={{width:220,flexShrink:0,background:T.surface,borderRight:'1px solid '+T.border,display:'flex',flexDirection:'column',height:'100vh',position:'sticky',top:0}}>
    <div style={{padding:'24px 20px 20px',borderBottom:'1px solid '+T.border}}><div style={{display:'flex',alignItems:'center',gap:12}}><div style={{width:40,height:40,borderRadius:12,background:CG,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:900,fontSize:18,color:'#080810',flexShrink:0,boxShadow:'0 4px 16px rgba(200,200,220,.2)'}}>S</div><div><div style={{fontSize:13,fontWeight:800,...CT,letterSpacing:-.2}}>SSP</div><div style={{fontSize:10,color:T.s2,letterSpacing:.5}}>COMMAND CENTER</div></div></div></div>
    <nav style={{flex:1,padding:'12px 10px',overflowY:'auto'}}>{NAV.map(n => { const isA=active===n.id; const al=alerts[n.id]||0; return <button key={n.id} onClick={()=>setActive(n.id)} style={{width:'100%',display:'flex',alignItems:'center',gap:12,padding:'11px 12px',borderRadius:10,border:'none',cursor:'pointer',marginBottom:2,transition:'all .15s',background:isA?'rgba(200,200,255,.08)':'transparent',borderLeft:isA?'2px solid '+T.silver:'2px solid transparent'}}><span style={{fontSize:15,width:20,textAlign:'center',opacity:isA?1:.5}}>{n.icon}</span><div style={{textAlign:'left',flex:1}}><div style={{fontSize:13,fontWeight:isA?700:500,color:isA?T.s3:T.s2}}>{n.label}</div><div style={{fontSize:10,color:T.muted}}>{n.desc}</div></div>{al>0 && <span style={{background:T.red,color:'#fff',borderRadius:10,padding:'1px 7px',fontSize:10,fontWeight:700}}>{al}</span>}</button>})}</nav>
    <div style={{padding:'16px 20px',borderTop:'1px solid '+T.border}}><div style={{display:'flex',alignItems:'center',gap:8}}><div style={{width:8,height:8,borderRadius:'50%',background:T.green,boxShadow:'0 0 8px '+T.green}}/><span style={{fontSize:11,color:T.s2}}>Live</span><span style={{fontSize:11,color:T.muted,marginLeft:'auto'}}>{new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span></div></div>
  </div>
}

function HomeModule({onNav}) {
  const kpis = [{label:'Monthly Revenue',value:'$42,650',sub:'+12% vs last month',color:T.green,icon:'💰',nav:'invoices'},{label:'Active Officers',value:'4',sub:'1 inactive',color:T.silver,icon:'◈',nav:'roster'},{label:'Open Invoices',value:'$36,850',sub:'3 pending, 1 overdue',color:T.gold,icon:'◧',nav:'invoices'},{label:'Hot Leads',value:'2',sub:'$57,000 pipeline',color:T.red,icon:'🔥',nav:'leads'},{label:'Upcoming Events',value:'3',sub:'Next 7 days',color:T.blue,icon:'📅',nav:'events'},{label:'Payroll Due',value:'$14,036',sub:'2 pending approval',color:T.purple,icon:'◫',nav:'payroll'}]
  const alerts = [{type:'danger',title:'Invoice Overdue',desc:'Midtown Mall — $6,200 overdue 8 days',nav:'invoices'},{type:'warning',title:'Hot Lead',desc:'Grady Hospital — $35,000 requires follow-up',nav:'leads'},{type:'info',title:'Shift Pending',desc:'Devon Clark — Tue 08:00 awaiting confirm',nav:'shifts'},{type:'success',title:'Payment Received',desc:'Ponce City Market — $5,800 paid',nav:'invoices'}]
  const tc = {danger:T.red,warning:T.gold,info:T.blue,success:T.green}
  const today = new Date()
  return <div style={{flex:1,overflowY:'auto'}}>
    <TopBar title='Good morning, Dijon' sub={today.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}/>
    <div style={{padding:'24px 32px',display:'flex',flexDirection:'column',gap:24}}>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:14}}>{kpis.map(k=><div key={k.label} className='card-hover' onClick={()=>onNav(k.nav)} style={{background:T.card,border:'1px solid '+T.border,borderRadius:14,padding:'18px 20px',position:'relative',overflow:'hidden',cursor:'pointer'}}><div style={{position:'absolute',top:0,left:0,right:0,height:2,background:k.color,opacity:.6}}/><div style={{display:'flex',justifyContent:'space-between',marginBottom:10}}><span style={{fontSize:11,color:T.muted,fontWeight:600,letterSpacing:1,textTransform:'uppercase'}}>{k.label}</span><span style={{fontSize:18,opacity:.5}}>{k.icon}</span></div><div style={{fontSize:26,fontWeight:800,color:k.color,letterSpacing:-.5}}>{k.value}</div><div style={{fontSize:11,color:T.s2,marginTop:6}}>{k.sub}</div></div>)}</div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
        <Card><div style={{fontSize:13,fontWeight:700,color:T.silver,marginBottom:16,display:'flex',justifyContent:'space-between',alignItems:'center'}}><span>Alerts & Activity</span><Pill color={T.red}>{alerts.filter(a=>a.type==='danger').length} urgent</Pill></div>{alerts.map((a,i)=><div key={i} onClick={()=>onNav(a.nav)} style={{display:'flex',gap:12,alignItems:'flex-start',padding:'12px 0',borderBottom:i<alerts.length-1?'1px solid '+T.border:'none',cursor:'pointer'}}><div style={{width:8,height:8,borderRadius:'50%',background:tc[a.type],marginTop:5,flexShrink:0,boxShadow:'0 0 6px '+tc[a.type]}}/><div><div style={{fontSize:13,fontWeight:600,color:T.text}}>{a.title}</div><div style={{fontSize:12,color:T.s2,marginTop:2}}>{a.desc}</div></div></div>)}</Card>
        <Card><div style={{fontSize:13,fontWeight:700,color:T.silver,marginBottom:16}}>Today's Coverage</div>{[{officer:'Marcus Reid',site:'Hartsfield-Jackson Airport',time:'06:00-14:00',status:'on-duty'},{officer:'Tasha Williams',site:'Buckhead Office Tower',time:'14:00-22:00',status:'standby'},{officer:'Janet Moore',site:'Airport',time:'22:00-06:00',status:'standby'},{officer:'Devon Clark',site:'Midtown Mall',time:'08:00-16:00',status:'confirmed'}].map((s,i)=><div key={i} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'10px 0',borderBottom:i<3?'1px solid '+T.border:'none'}}><div><div style={{fontSize:13,fontWeight:600,color:T.text}}>{s.officer}</div><div style={{fontSize:11,color:T.s2}}>{s.site}</div></div><div style={{textAlign:'right'}}><div style={{fontSize:11,fontFamily:'monospace',color:T.s2}}>{s.time}</div><Pill color={s.status==='on-duty'?T.green:T.gold} style={{marginTop:4,display:'inline-block'}}>{s.status}</Pill></div></div>)}</Card>
      </div>
    </div>
  </div>
}

function EventsModule() {
  const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
  const [mo,setMo]=useState(new Date().getMonth()); const [yr,setYr]=useState(new Date().getFullYear())
  const [events,setEvents]=useState([{id:1,title:'Hartsfield-Jackson Security Detail',client:'Airport Authority',date:'2026-04-10',end:'2026-04-10',type:'contract',officers:['Marcus Reid','Janet Moore'],notes:'VIP arrival coverage'},{id:2,title:'Buckhead Tower Monthly Patrol',client:'Buckhead Properties',date:'2026-04-14',end:'2026-04-14',type:'patrol',officers:['Tasha Williams'],notes:'Standard monthly walkthrough'},{id:3,title:'Midtown Mall Grand Opening',client:'Midtown Mall Mgmt',date:'2026-04-18',end:'2026-04-20',type:'event',officers:['Devon Clark','Marcus Reid','Tasha Williams'],notes:'High-profile 3-day event'},{id:4,title:'Emory University Graduation',client:'Emory University',date:'2026-05-08',end:'2026-05-08',type:'event',officers:['Janet Moore','Marcus Reid'],notes:'Annual commencement security'},{id:5,title:'Atlanta Tech Campus Audit',client:'Atlanta Tech',date:'2026-04-22',end:'2026-04-22',type:'meeting',officers:[],notes:'Security assessment'},{id:6,title:'Grady Hospital Proposal',client:'Grady Memorial',date:'2026-04-09',end:'2026-04-09',type:'meeting',officers:[],notes:'Initial consultation'}])
  const [sel,setSel]=useState(null); const [showAdd,setShowAdd]=useState(false)
  const [form,setForm]=useState({title:'',client:'',date:'',end:'',type:'event',officers:'',notes:''})
  const TC={contract:T.green,patrol:T.blue,event:T.gold,meeting:T.purple}
  const TI={contract:'📋',patrol:'🛡',event:'🎯',meeting:'🤝'}
  const startDay=new Date(yr,mo,1).getDay(); const daysInMonth=new Date(yr,mo+1,0).getDate()
  const cells=[...Array(startDay).fill(null),...Array.from({length:daysInMonth},(_,i)=>i+1)]
  const eventsInMonth=events.filter(e=>{const d=new Date(e.date);return d.getFullYear()===yr&&d.getMonth()===mo})
  const byDay={}; eventsInMonth.forEach(e=>{const d=new Date(e.date).getDate();(byDay[d]=byDay[d]||[]).push(e)})
  const isToday=d=>d&&new Date(yr,mo,d).toDateString()===new Date().toDateString()
  const selEvent=sel?events.find(e=>e.id===sel):null
  const add=()=>{if(!form.title||!form.date)return;setEvents(ev=>[...ev,{...form,id:Date.now(),officers:form.officers.split(',').map(o=>o.trim()).filter(Boolean)}]);setForm({title:'',client:'',date:'',end:'',type:'event',officers:'',notes:''});setShowAdd(false)}
  return <div style={{flex:1,overflowY:'auto'}}>
    <TopBar title='Company Events' sub='Calendar, contracts & coverage overview' actions={<Btn onClick={()=>setShowAdd(!showAdd)} style={{fontSize:12}}>+ Add Event</Btn>}/>
    <div style={{padding:'24px 32px',display:'flex',flexDirection:'column',gap:20}}>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12}}><StatCard label='Total Events' value={events.length} color={T.silver} icon='📅'/><StatCard label='Contracts' value={events.filter(e=>e.type==='contract').length} color={T.green} icon='📋'/><StatCard label='This Month' value={eventsInMonth.length} color={T.blue} icon='📆'/><StatCard label='Officers Needed' value={[...new Set(events.flatMap(e=>e.officers))].length} color={T.gold} icon='◈'/></div>
      {showAdd && <Card><div style={{fontSize:13,fontWeight:700,color:T.silver,marginBottom:14}}>New Event</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10}}><Inp val={form.title} onChange={v=>setForm(f=>({...f,title:v}))} ph='Event title' icon='📅'/><Inp val={form.client} onChange={v=>setForm(f=>({...f,client:v}))} ph='Client name' icon='◈'/><Inp val={form.date} onChange={v=>setForm(f=>({...f,date:v}))} ph='Start date' type='date'/><Inp val={form.end} onChange={v=>setForm(f=>({...f,end:v}))} ph='End date' type='date'/><Sel val={form.type} onChange={v=>setForm(f=>({...f,type:v}))} opts={[{v:'event',l:'Event'},{v:'contract',l:'Contract'},{v:'patrol',l:'Patrol'},{v:'meeting',l:'Meeting'}]}/><Inp val={form.officers} onChange={v=>setForm(f=>({...f,officers:v}))} ph='Officers (comma-sep)'/><Btn onClick={add} style={{fontSize:12}}>+ Add</Btn></div></Card>}
      <div style={{display:'grid',gridTemplateColumns:'1fr 320px',gap:20}}>
        <Card><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20}}><button onClick={()=>{if(mo===0){setMo(11);setYr(y=>y-1);}else setMo(m=>m-1)}} style={{background:'none',border:'1px solid '+T.border2,borderRadius:8,color:T.silver,fontSize:16,width:32,height:32,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center'}}>&#8249;</button><div style={{...CT,fontSize:16,fontWeight:800,letterSpacing:-.3}}>{MONTHS[mo].toUpperCase()+' '+yr}</div><button onClick={()=>{if(mo===11){setMo(0);setYr(y=>y+1);}else setMo(m=>m+1)}} style={{background:'none',border:'1px solid '+T.border2,borderRadius:8,color:T.silver,fontSize:16,width:32,height:32,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center'}}>&#8250;</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(7,1fr)',gap:3}}>{['Su','Mo','Tu','We','Th','Fr','Sa'].map(d=><div key={d} style={{fontSize:10,fontWeight:700,color:T.muted,textAlign:'center',padding:'4px 0',letterSpacing:1}}>{d}</div>)}{cells.map((d,i)=>{const evs=d?(byDay[d]||[]):[];return <div key={i} onClick={()=>evs.length>0&&setSel(evs[0].id)} style={{minHeight:52,background:isToday(d)?'rgba(200,200,255,.06)':evs.length?'rgba(64,128,255,.04)':'rgba(255,255,255,.01)',border:'1px solid '+(isToday(d)?T.silver2:T.border),borderRadius:8,padding:'4px 6px',cursor:evs.length?'pointer':'default'}}>{d&&<div style={{fontSize:11,fontWeight:isToday(d)?800:400,color:isToday(d)?T.s3:T.s2,marginBottom:2}}>{d}</div>}{evs.slice(0,2).map((e,j)=><div key={j} style={{fontSize:9,background:TC[e.type]+'25',color:TC[e.type],padding:'2px 4px',borderRadius:3,marginBottom:1,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{e.title.substring(0,14)}</div>)}{evs.length>2&&<div style={{fontSize:9,color:T.muted}}>+{evs.length-2}</div>}</div>})}</div></Card>
        <div style={{display:'flex',flexDirection:'column',gap:12}}>{selEvent?<Card><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:12}}><div style={{...CT,fontSize:15,fontWeight:700}}>{selEvent.title}</div><button onClick={()=>setSel(null)} style={{background:'none',border:'none',color:T.s2,cursor:'pointer',fontSize:18}}>×</button></div><Pill color={TC[selEvent.type]}>{TI[selEvent.type]+' '+selEvent.type}</Pill><Divider/><div style={{fontSize:12,color:T.s2,marginBottom:8}}>📍 {selEvent.client}</div><div style={{fontSize:12,color:T.s2,marginBottom:8}}>📅 {selEvent.date+(selEvent.end&&selEvent.end!==selEvent.date?' → '+selEvent.end:'')}</div>{selEvent.notes&&<div style={{fontSize:12,color:T.s2,marginBottom:12}}>📝 {selEvent.notes}</div>}<div style={{fontSize:11,fontWeight:700,color:T.muted,letterSpacing:1,textTransform:'uppercase',marginBottom:8}}>Officers</div>{selEvent.officers.length>0?selEvent.officers.map((o,i)=><div key={i} style={{fontSize:13,color:T.text,padding:'6px 0',borderBottom:i<selEvent.officers.length-1?'1px solid '+T.border:'none'}}>◈ {o}</div>):<div style={{fontSize:12,color:T.muted}}>No officers assigned</div>}</Card>:<Card style={{textAlign:'center',padding:'32px 20px'}}><div style={{fontSize:32,marginBottom:8}}>📅</div><div style={{fontSize:13,color:T.s2}}>Click an event to view details</div></Card>}<Card><div style={{fontSize:12,fontWeight:700,color:T.silver,marginBottom:12}}>Upcoming Events</div>{events.sort((a,b)=>new Date(a.date)-new Date(b.date)).filter(e=>new Date(e.date)>=new Date()).slice(0,4).map((e,i)=><div key={i} onClick={()=>setSel(e.id)} style={{display:'flex',gap:10,padding:'10px 0',borderBottom:i<3?'1px solid '+T.border:'none',cursor:'pointer',alignItems:'flex-start'}}><div style={{width:36,height:36,borderRadius:8,background:TC[e.type]+'20',border:'1px solid '+TC[e.type]+'40',display:'flex',alignItems:'center',justifyContent:'center',fontSize:14,flexShrink:0}}>{TI[e.type]}</div><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,fontWeight:600,color:T.text,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{e.title}</div><div style={{fontSize:11,color:T.s2,marginTop:2}}>{e.date+' · '+e.client}</div></div></div>)}</Card></div>
      </div>
    </div>
  </div>
}

function ShiftsModule() {
  const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
  const [shifts,setShifts]=useState([{id:1,officer:'Marcus Reid',site:'Hartsfield-Jackson Airport',day:'Mon',start:'06:00',end:'14:00',status:'confirmed'},{id:2,officer:'Tasha Williams',site:'Buckhead Office Tower',day:'Mon',start:'14:00',end:'22:00',status:'confirmed'},{id:3,officer:'Devon Clark',site:'Midtown Mall',day:'Tue',start:'08:00',end:'16:00',status:'pending'},{id:4,officer:'Janet Moore',site:'Hartsfield-Jackson Airport',day:'Wed',start:'22:00',end:'06:00',status:'confirmed'},{id:5,officer:'Marcus Reid',site:'Emory University',day:'Thu',start:'07:00',end:'15:00',status:'confirmed'},{id:6,officer:'Tasha Williams',site:'Midtown Mall',day:'Fri',start:'10:00',end:'18:00',status:'pending'}])
  const [form,setForm]=useState({officer:'',site:'',day:'Mon',start:'08:00',end:'16:00'})
  const [ai,setAi]=useState(''); const [loading,setLoading]=useState(false); const [showAdd,setShowAdd]=useState(false); const [view,setView]=useState('list')
  const officers=[...new Set(shifts.map(s=>s.officer))]
  const add=()=>{if(!form.officer||!form.site)return;setShifts(s=>[...s,{...form,id:Date.now(),status:'pending'}]);setForm({officer:'',site:'',day:'Mon',start:'08:00',end:'16:00'});setShowAdd(false)}
  const opt=async()=>{setLoading(true);setAi('');const t=await aiCall('Review shifts for Special Services Protection Atlanta and give 2-3 scheduling recommendations: '+shifts.map(s=>s.officer+' at '+s.site+' '+s.day+' '+s.start+'-'+s.end).join('; ')+'.');setAi(t);setLoading(false)}
  return <div style={{flex:1,overflowY:'auto'}}>
    <TopBar title='Shift Manager' sub='Officer scheduling & coverage planning' actions={<><Btn v='g' onClick={opt} disabled={loading} style={{fontSize:12}}>{loading?'Analyzing...':'✦ AI Optimize'}</Btn><Btn onClick={()=>setShowAdd(!showAdd)} style={{fontSize:12}}>+ Add Shift</Btn></>}/>
    <div style={{padding:'24px 32px',display:'flex',flexDirection:'column',gap:20}}>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12}}><StatCard label='Total Shifts' value={shifts.length} color={T.silver} icon='⏱'/><StatCard label='Confirmed' value={shifts.filter(s=>s.status==='confirmed').length} color={T.green} icon='✓'/><StatCard label='Pending' value={shifts.filter(s=>s.status==='pending').length} color={T.gold} icon='◌'/><StatCard label='Officers Active' value={officers.length} color={T.blue} icon='◈'/></div>
      <AIBlock text={ai}/>
      <div style={{display:'flex',gap:2,background:T.card,borderRadius:10,padding:4,border:'1px solid '+T.border,width:'fit-content'}}>{[['list','List View'],['grid','Weekly Grid']].map(([k,l])=><button key={k} onClick={()=>setView(k)} style={{padding:'7px 16px',background:view===k?'rgba(255,255,255,.08)':'transparent',border:'none',borderRadius:8,color:view===k?T.s3:T.s2,fontSize:12,fontWeight:view===k?700:500,cursor:'pointer'}}>{l}</button>)}</div>
      {showAdd && <Card><div style={{fontSize:13,fontWeight:700,color:T.silver,marginBottom:14}}>New Shift</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:10}}><Inp val={form.officer} onChange={v=>setForm(f=>({...f,officer:v}))} ph='Officer' icon='◈'/><Inp val={form.site} onChange={v=>setForm(f=>({...f,site:v}))} ph='Site' icon='⬡'/><Sel val={form.day} onChange={v=>setForm(f=>({...f,day:v}))} opts={DAYS.map(d=>({v:d,l:d}))}/><Inp val={form.start} onChange={v=>setForm(f=>({...f,start:v}))} ph='Start' type='time'/><Inp val={form.end} onChange={v=>setForm(f=>({...f,end:v}))} ph='End' type='time'/><Btn onClick={add} style={{fontSize:12}}>+ Add</Btn></div></Card>}
      {view==='list' && <div style={{display:'flex',flexDirection:'column',gap:10}}>{shifts.map(s=><div key={s.id} style={{background:T.card,border:'1px solid '+T.border,borderRadius:12,padding:'16px 20px',display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:12,borderLeft:'3px solid '+(s.status==='confirmed'?T.green:T.gold)}}><div><div style={{fontWeight:700,color:T.text,fontSize:14,marginBottom:3}}>{s.officer}</div><div style={{fontSize:12,color:T.s2}}>{s.site}</div></div><div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><Pill color={T.silver}>{s.day}</Pill><span style={{fontFamily:'monospace',fontSize:12,color:T.s2}}>{s.start+'–'+s.end}</span><Pill color={s.status==='confirmed'?T.green:T.gold}>{s.status}</Pill>{s.status==='pending'&&<Btn v='success' style={{fontSize:11,padding:'4px 12px'}} onClick={()=>setShifts(sh=>sh.map(x=>x.id===s.id?{...x,status:'confirmed'}:x))}>Confirm</Btn>}<button onClick={()=>setShifts(sh=>sh.filter(x=>x.id!==s.id))} style={{background:'none',border:'1px solid '+T.border2,borderRadius:6,color:T.s2,fontSize:11,padding:'4px 10px',cursor:'pointer'}}>Remove</button></div></div>)}</div>}
      {view==='grid' && <div style={{overflowX:'auto'}}><div style={{display:'grid',gridTemplateColumns:'140px repeat(7,1fr)',gap:4,minWidth:700}}><div style={{color:T.muted,fontSize:11,padding:'4px 8px',fontWeight:700,textTransform:'uppercase',letterSpacing:1}}>Officer</div>{DAYS.map(d=><div key={d} style={{fontSize:11,fontWeight:700,color:T.silver,textAlign:'center',padding:'4px 0',letterSpacing:1}}>{d.toUpperCase()}</div>)}{officers.flatMap(officer=>[<div key={officer+'n'} style={{color:T.text,fontSize:12,padding:'8px',display:'flex',alignItems:'center',fontWeight:600}}>{officer.split(' ')[0]}</div>,...DAYS.map(day=>{const s=shifts.find(x=>x.officer===officer&&x.day===day);return <div key={officer+day} style={{background:s?(s.status==='confirmed'?'rgba(16,217,138,.08)':'rgba(212,168,67,.08)'):'rgba(255,255,255,.02)',border:'1px solid '+(s?(s.status==='confirmed'?'rgba(16,217,138,.2)':'rgba(212,168,67,.2)'):T.border),borderRadius:8,padding:'6px 4px',fontSize:10,color:s?(s.status==='confirmed'?T.green:T.gold):T.muted,textAlign:'center',minHeight:44,display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',gap:2}}>{s?<><span>{s.start}</span><span style={{opacity:.6}}>{'–'+s.end}</span></>:'—'}</div>})])}</div></div>}
    </div>
  </div>
}

function RosterModule() {
  const [officers]=useState([{id:1,name:'Marcus Reid',role:'Senior Officer',cert:'Armed',status:'active',hired:'2021-03-15',phone:'404-555-0101',clearance:'Level 3',email:'m.reid@ssp.com'},{id:2,name:'Tasha Williams',role:'Officer',cert:'Unarmed',status:'active',hired:'2022-07-01',phone:'404-555-0102',clearance:'Level 1',email:'t.williams@ssp.com'},{id:3,name:'Devon Clark',role:'Officer',cert:'Armed',status:'active',hired:'2023-01-10',phone:'404-555-0103',clearance:'Level 2',email:'d.clark@ssp.com'},{id:4,name:'Janet Moore',role:'Supervisor',cert:'Armed',status:'active',hired:'2020-06-20',phone:'404-555-0104',clearance:'Level 4',email:'j.moore@ssp.com'},{id:5,name:'Ray Thompson',role:'Officer',cert:'Unarmed',status:'inactive',hired:'2022-11-05',phone:'404-555-0105',clearance:'Level 1',email:'r.thompson@ssp.com'}])
  const [search,setSearch]=useState(''); const [sel,setSel]=useState(null); const [bio,setBio]=useState(''); const [loading,setLoading]=useState(false)
  const genBio=async o=>{setLoading(true);setBio('');const t=await aiCall('Write 2-sentence professional security officer profile for '+o.name+', '+o.role+', '+o.cert+' certified, hired '+o.hired+' at Special Services Protection Atlanta. Clearance: '+o.clearance+'.');setBio(t);setLoading(false)}
  const filtered=officers.filter(o=>o.name.toLowerCase().includes(search.toLowerCase())||o.role.toLowerCase().includes(search.toLowerCase()))
  return <div style={{flex:1,overflowY:'auto'}}>
    <TopBar title='Officer Roster' sub='Personnel management & profiles' actions={<><Pill color={T.green}>{officers.filter(o=>o.status==='active').length} Active</Pill><Pill color={T.red}>{officers.filter(o=>o.status==='inactive').length} Inactive</Pill></>}/>
    <div style={{padding:'24px 32px',display:'flex',flexDirection:'column',gap:20}}>
      <Inp val={search} onChange={setSearch} ph='Search by name or role...' icon='⬡'/>
      {bio && <AIBlock text={bio} color={T.blue} label='AI Profile'/>}
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(300px,1fr))',gap:14}}>{filtered.map(o=><div key={o.id} onClick={()=>setSel(sel===o.id?null:o.id)} className='card-hover' style={{background:T.card,border:'1px solid '+(sel===o.id?T.silver2:T.border),borderRadius:14,padding:20,cursor:'pointer',transition:'all .2s'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:14}}><div style={{display:'flex',alignItems:'center',gap:12}}><div style={{width:44,height:44,borderRadius:12,background:'linear-gradient(135deg,#2a2a4a,#3a3a6a)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:15,fontWeight:700,color:T.s3,flexShrink:0}}>{o.name.split(' ').map(n=>n[0]).join('')}</div><div><div style={{fontWeight:700,color:T.text,fontSize:14}}>{o.name}</div><div style={{fontSize:12,color:T.s2,marginTop:1}}>{o.role}</div></div></div><Pill color={o.status==='active'?T.green:T.red}>{o.status}</Pill></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Pill color={o.cert==='Armed'?T.gold:T.s2}>{o.cert}</Pill><Pill color={T.purple}>{o.clearance}</Pill><Pill color={T.s2}>{'Since '+o.hired}</Pill></div>{sel===o.id&&<><Divider/><div style={{fontSize:12,color:T.s2,marginBottom:4}}>📞 {o.phone}</div><div style={{fontSize:12,color:T.s2,marginBottom:12}}>✉ {o.email}</div><Btn v='g' onClick={e=>{e.stopPropagation();genBio(o)}} disabled={loading} style={{fontSize:12,width:'100%',justifyContent:'center'}}>{loading?'Generating...':'✦ Generate Profile'}</Btn></>}</div>)}</div>
    </div>
  </div>
}

const STATUSES=['Draft','Sent','Viewed','Overdue','Paid','Cancelled']
const SC={Draft:{bg:'rgba(255,255,255,.04)',text:'#808098',border:'rgba(255,255,255,.08)'},Sent:{bg:'rgba(64,128,255,.08)',text:'#6090ff',border:'rgba(64,128,255,.2)'},Viewed:{bg:'rgba(212,168,67,.08)',text:'#d4a843',border:'rgba(212,168,67,.2)'},Overdue:{bg:'rgba(240,80,80,.08)',text:'#f05050',border:'rgba(240,80,80,.2)'},Paid:{bg:'rgba(16,217,138,.08)',text:'#10d98a',border:'rgba(16,217,138,.2)'},Cancelled:{bg:'rgba(128,128,160,.06)',text:'#606080',border:'rgba(128,128,160,.15)'}}
const ISEED=[{id:'INV-001',client:'Hartsfield-Jackson Airport',email:'billing@hjairport.com',amount:12500,due:'2026-05-15',status:'Sent',issued:'2026-03-01',reminders:0,notes:'Event Security Detail',source:'manual'},{id:'INV-002',client:'Buckhead Properties LLC',email:'ap@buckhead.com',amount:8750,due:'2026-05-20',status:'Viewed',issued:'2026-03-15',reminders:1,notes:'Monthly Retainer',source:'manual'},{id:'INV-003',client:'Midtown Mall Management',email:'fin@midtown.com',amount:6200,due:'2026-03-30',status:'Overdue',issued:'2026-03-10',reminders:2,notes:'Executive Protection',source:'manual'},{id:'INV-004',client:'Atlanta Tech Campus',email:'acc@atc.com',amount:9400,due:'2026-05-30',status:'Draft',issued:'2026-04-01',reminders:0,notes:'VIP Detail',source:'manual'},{id:'INV-005',client:'Ponce City Market',email:'bill@pcm.com',amount:5800,due:'2026-03-10',status:'Paid',issued:'2026-02-10',reminders:0,notes:'Weekend Security',source:'manual'}]
const SBadge=({status})=>{const s=SC[status]||SC.Draft;return <span style={{background:s.bg,color:s.text,border:'1px solid '+s.border,padding:'3px 12px',fontSize:11,fontWeight:600,letterSpacing:.5,textTransform:'uppercase',borderRadius:20}}>{status}</span>}

function GmailModal({onClose,onAction,invoices=[],inline}) {
  const [tab,setTab]=useState('agent'); const [phase,setPhase]=useState('idle')
  const [found,setFound]=useState([]); const [sel,setSel]=useState({})
  const [log,setLog]=useState([])
  const [msgs,setMsgs]=useState([{role:'assistant',text:'SSP Gmail Agent online. I can scan your inbox for invoices, send payment reminders, draft follow-ups, and manage your billing workflow.'}])
  const [input,setInput]=useState(''); const [loading,setLoading]=useState(false)
  const QUICK=['Check my overdue invoices','Send reminder to Midtown Mall','Summarize unpaid accounts','Draft follow-up for Buckhead Properties']
  const scan=async()=>{
    setPhase('scanning');setLog([])
    setLog(l=>[...l,{t:new Date().toLocaleTimeString(),m:'Connecting to Gmail via MCP...'}])
    const result=await gmailCall('Search Gmail for invoice, billing, or payment emails from last 90 days.','Invoice extraction agent for SSP. Search Gmail. Respond ONLY with JSON array: [{"client":"Name","email":"e@mail.com","amount":1234,"due":"YYYY-MM-DD","notes":"desc"}]. Return [] if none.')
    setLog(l=>[...l,{t:new Date().toLocaleTimeString(),m:'Parsing results...'}])
    let parsed=[];try{const m=result.replace(/```json|```/g,'').match(/\[[\s\S]*\]/);if(m)parsed=JSON.parse(m[0])}catch{}
    if(!Array.isArray(parsed))parsed=[]
    setLog(l=>[...l,{t:new Date().toLocaleTimeString(),m:'Found '+parsed.length+' invoice email(s).'}])
    const enriched=parsed.map(p=>({...p,id:uid(),status:'Draft',reminders:0,source:'gmail',amount:parseFloat(p.amount)||0,issued:todayStr()}))
    setFound(enriched);const s={};enriched.forEach(e=>s[e.id]=true);setSel(s);setPhase('results')
  }
  const send=async()=>{
    if(!input.trim()||loading)return
    const txt=input.trim();setInput('');setLoading(true)
    setMsgs(m=>[...m,{role:'user',text:txt}])
    const inv=invoices.map(i=>i.id+' '+i.client+' $'+i.amount+' due '+i.due+' '+i.status).join('\n')
    const result=await gmailCall(txt,'Gmail & invoice agent for SSP Atlanta. Today:'+todayStr()+'\nINVOICES:\n'+inv+'\nEmit: ACTION: {"type":"update","id":"INV-XXX","status":"Status"} or ACTION: {"type":"remind","id":"INV-XXX"}. Be concise.')
    const re=/ACTION:\s*(\{[^\n]+\})/g;let m
    while((m=re.exec(result))!==null){try{onAction(JSON.parse(m[1]))}catch{}}
    setMsgs(ms=>[...ms,{role:'assistant',text:result.replace(/ACTION:\s*\{[^\n]+\}/g,'').trim()}])
    setLoading(false)
  }
  const body=<div>
    <div style={{display:'flex',borderBottom:'1px solid '+T.border}}>{[['agent','✉ AI Agent'],['scan','⬡ Scan Invoices']].map(([k,l])=><button key={k} onClick={()=>setTab(k)} style={{flex:1,padding:'12px',background:'none',border:'none',borderBottom:tab===k?'2px solid '+T.silver:'2px solid transparent',color:tab===k?T.s3:T.s2,fontSize:13,fontWeight:600,cursor:'pointer'}}>{l}</button>)}</div>
    <div style={{padding:20}}>
      {tab==='agent' && <div style={{display:'flex',flexDirection:'column',gap:12}}><div style={{minHeight:160,maxHeight:320,overflowY:'auto',display:'flex',flexDirection:'column',gap:8}}>{msgs.map((m,i)=><div key={i} style={{display:'flex',justifyContent:m.role==='user'?'flex-end':'flex-start'}}><div style={{maxWidth:'85%',padding:'10px 14px',background:m.role==='user'?'rgba(64,128,255,.15)':T.card2,border:'1px solid '+(m.role==='user'?'rgba(64,128,255,.3)':T.border),color:T.text,fontSize:13,lineHeight:1.6,whiteSpace:'pre-wrap',borderRadius:10}}>{m.text}</div></div>)}{loading&&<div style={{display:'flex'}}><div style={{padding:'10px 14px',background:T.card,border:'1px solid '+T.border,color:T.s2,fontSize:13,borderRadius:10}}>Thinking...</div></div>}</div>{msgs.length<=1&&<div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{QUICK.map((q,i)=><button key={i} onClick={()=>setInput(q)} style={{padding:'5px 10px',background:'rgba(255,255,255,.04)',border:'1px solid '+T.border,color:T.s2,fontSize:11,borderRadius:6,cursor:'pointer'}}>{q}</button>)}</div>}<div style={{display:'flex',gap:8,paddingTop:12,borderTop:'1px solid '+T.border}}><Inp val={input} onChange={setInput} ph='Ask the Gmail agent...' style={{flex:1}} icon='✉'/><Btn onClick={send} disabled={loading||!input.trim()} style={{padding:'9px 16px'}}>Send</Btn></div></div>}
      {tab==='scan' && <>{phase==='idle'&&<><p style={{fontSize:13,color:T.s2,lineHeight:1.7,marginBottom:16}}>Connect to Gmail and auto-extract invoice details.</p><Btn onClick={scan} style={{width:'100%',justifyContent:'center',padding:'11px'}}>Scan Gmail Inbox</Btn></>}{phase==='scanning'&&<div style={{textAlign:'center',padding:'16px 0'}}><div style={{fontSize:13,color:T.silver,fontWeight:600,marginBottom:12}}>Scanning...</div><div style={{background:T.card,borderRadius:10,padding:14,textAlign:'left'}}>{log.map((l,i)=><div key={i} style={{fontSize:12,color:T.s2,marginBottom:4,fontFamily:'monospace'}}>{l.t+' '+l.m}</div>)}</div></div>}{phase==='results'&&found.length===0&&<div style={{textAlign:'center',padding:24}}><div style={{fontSize:32,marginBottom:10}}>📭</div><p style={{fontSize:13,color:T.s2}}>No invoice emails found. Connect Gmail in Claude.ai Integrations.</p></div>}{phase==='results'&&found.length>0&&<>{found.map(f=><div key={f.id} onClick={()=>setSel(s=>({...s,[f.id]:!s[f.id]}))} style={{border:'1px solid '+(sel[f.id]?T.silver2:T.border),borderRadius:10,padding:14,marginBottom:8,cursor:'pointer',background:sel[f.id]?'rgba(200,200,255,.05)':T.card,transition:'all .15s'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontWeight:700,color:T.text,fontSize:13}}>{f.client}</div><div style={{fontSize:11,color:T.s2,marginTop:2}}>{f.notes+' · Due '+(f.due||'TBD')}</div></div><span style={{fontWeight:800,color:T.s3,fontSize:15}}>{fmt(f.amount)}</span></div></div>)}<Btn onClick={()=>onAction({type:'import',items:found.filter(f=>sel[f.id])})} style={{width:'100%',justifyContent:'center',marginTop:8}}>{'Import '+found.filter(f=>sel[f.id]).length+' Invoice(s)'}</Btn></> }</>}
    </div>
  </div>
  if(inline)return <div style={{background:T.card,border:'1px solid '+T.border,borderRadius:14,overflow:'hidden'}}>{body}</div>
  return <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.75)',backdropFilter:'blur(8px)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:200}}><div style={{background:T.surface,border:'1px solid '+T.border2,borderRadius:16,width:520,maxHeight:'90vh',display:'flex',flexDirection:'column',boxShadow:'0 24px 64px rgba(0,0,0,.6)',overflow:'hidden'}}><div style={{padding:'20px 24px',borderBottom:'1px solid '+T.border,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{display:'flex',alignItems:'center',gap:12}}><div style={{width:36,height:36,borderRadius:10,background:'linear-gradient(135deg,#1040a0,#4080ff)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:16}}>✉</div><div><div style={{fontWeight:700,color:T.text,fontSize:15}}>Gmail Integration</div><div style={{fontSize:11,color:T.s2}}>AI Agent & Invoice Scanner</div></div></div><button onClick={onClose} style={{background:'none',border:'1px solid '+T.border,color:T.s2,fontSize:18,cursor:'pointer',width:32,height:32,borderRadius:8,display:'flex',alignItems:'center',justifyContent:'center'}}>×</button></div><div style={{overflowY:'auto'}}>{body}</div></div></div>
}

function InvoiceModule() {
  const [invoices,setInvoices]=useState(ISEED)
  const [subTab,setSubTab]=useState('list'); const [filter,setFilter]=useState('All')
  const [showNew,setShowNew]=useState(false); const [showGmail,setShowGmail]=useState(false)
  const [expanded,setExpanded]=useState(null); const [toasts,setToasts]=useState([])
  const [nf,setNf]=useState({client:'',email:'',amount:'',due:'',notes:''})
  const toast=(msg,type='i')=>{const id=Date.now();setToasts(t=>[...t,{id,msg,type}]);setTimeout(()=>setToasts(t=>t.filter(x=>x.id!==id)),4000)}
  const handleAct=act=>{if(act.type==='update'){setInvoices(l=>l.map(i=>i.id===act.id?{...i,status:act.status}:i));toast(act.id+' → '+act.status,'s')}else if(act.type==='remind'){setInvoices(l=>l.map(i=>i.id===act.id?{...i,reminders:i.reminders+1}:i));toast('Reminder: '+act.id)}else if(act.type==='import'&&act.items){setInvoices(l=>[...act.items,...l]);toast('Imported '+act.items.length+' invoice(s)','s')}}
  const save=()=>{if(!nf.client||!nf.amount||!nf.due)return;setInvoices(l=>[{...nf,amount:parseFloat(nf.amount),status:'Draft',issued:todayStr(),reminders:0,id:uid(),source:'manual'},...l]);setShowNew(false);setNf({client:'',email:'',amount:'',due:'',notes:''});toast('Invoice created','s')}
  const out=invoices.filter(i=>!['Paid','Cancelled'].includes(i.status)).reduce((s,i)=>s+i.amount,0)
  const coll=invoices.filter(i=>i.status==='Paid').reduce((s,i)=>s+i.amount,0)
  const filt=filter==='All'?invoices:invoices.filter(i=>i.status===filter)
  const rate=invoices.length?Math.round(invoices.filter(i=>i.status==='Paid').length/invoices.length*100):0
  return <div style={{flex:1,overflowY:'auto'}}>
    <div style={{position:'fixed',top:16,right:16,zIndex:500,display:'flex',flexDirection:'column',gap:8}}>{toasts.map(t=><div key={t.id} style={{background:T.surface,border:'1px solid '+(t.type==='s'?T.green:T.border2),color:t.type==='s'?T.green:T.silver,padding:'10px 16px',fontSize:12,borderRadius:10,boxShadow:'0 8px 24px rgba(0,0,0,.4)',fontWeight:600}}>{t.type==='s'?'✓ ':''}{t.msg}</div>)}</div>
    {showNew&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.7)',backdropFilter:'blur(8px)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:200}}><div style={{background:T.surface,border:'1px solid '+T.border2,borderRadius:16,padding:28,width:440}}><div style={{fontSize:16,fontWeight:700,color:T.text,marginBottom:20}}>New Invoice</div>{[['Client Name','client','text'],['Client Email','email','email'],['Amount ($)','amount','number'],['Due Date','due','date'],['Service Notes','notes','text']].map(([l,k,tp])=><div key={k} style={{marginBottom:14}}><label style={{fontSize:11,color:T.s2,fontWeight:600,letterSpacing:.5,textTransform:'uppercase',display:'block',marginBottom:6}}>{l}</label><Inp val={nf[k]} onChange={v=>setNf(f=>({...f,[k]:v}))} ph={l} type={tp}/></div>)}<div style={{display:'flex',gap:10,marginTop:20}}><Btn v='g' onClick={()=>setShowNew(false)} style={{flex:1,justifyContent:'center'}}>Cancel</Btn><Btn onClick={save} style={{flex:1,justifyContent:'center'}}>Create Invoice</Btn></div></div></div>}
    {showGmail&&<GmailModal onClose={()=>setShowGmail(false)} onAction={handleAct} invoices={invoices}/>}
    <TopBar title='Invoice Management' sub='Billing, collections & Gmail integration' actions={<><Btn v='glass' onClick={()=>setShowGmail(true)} style={{fontSize:12}} icon='✉'>Gmail</Btn><Btn onClick={()=>setShowNew(true)} style={{fontSize:12}}>+ New Invoice</Btn></>}/>
    <div style={{padding:'24px 32px',display:'flex',flexDirection:'column',gap:20}}>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:14}}><StatCard label='Outstanding' value={fmt(out)} sub='Pending collection' color={T.silver} icon='◧'/><StatCard label='Collected' value={fmt(coll)} sub='Paid invoices' color={T.green} icon='✓'/><StatCard label='Overdue' value={invoices.filter(i=>i.status==='Overdue').length+' Accts'} sub='Require action' color={T.red} icon='⚠'/><StatCard label='Collection Rate' value={rate+'%'} sub='Overall performance' color={T.gold} icon='◎'/></div>
      <div style={{display:'flex',gap:2,background:T.card,borderRadius:12,padding:4,border:'1px solid '+T.border}}>{[['list','◧  Invoices'],['analytics','◈  Analytics'],['agent','✉  Gmail Agent']].map(([k,l])=><button key={k} onClick={()=>setSubTab(k)} style={{flex:1,padding:'8px 16px',background:subTab===k?'rgba(255,255,255,.08)':'transparent',border:'none',borderRadius:9,color:subTab===k?T.s3:T.s2,fontSize:12,fontWeight:subTab===k?700:500,cursor:'pointer'}}>{l}</button>)}</div>
      {subTab==='list'&&<><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{['All',...STATUSES].map(s=><button key={s} onClick={()=>setFilter(s)} style={{padding:'5px 14px',background:filter===s?'rgba(255,255,255,.08)':'transparent',border:'1px solid '+(filter===s?T.silver2:T.border),color:filter===s?T.s3:T.s2,fontSize:12,fontWeight:filter===s?600:400,cursor:'pointer',borderRadius:20}}>{s}</button>)}</div><div style={{display:'flex',flexDirection:'column',gap:10}}>{filt.map(inv=><div key={inv.id} onClick={()=>setExpanded(expanded===inv.id?null:inv.id)} style={{background:T.card,border:'1px solid '+(expanded===inv.id?T.border2:T.border),borderRadius:14,padding:'18px 22px',cursor:'pointer',borderLeft:'3px solid '+(SC[inv.status]?.text||T.border)}}><div style={{display:'flex',justifyContent:'space-between',flexWrap:'wrap',gap:12}}><div style={{flex:1,minWidth:0}}><div style={{display:'flex',alignItems:'center',gap:10,marginBottom:6,flexWrap:'wrap'}}><span style={{fontWeight:700,color:T.text,fontSize:15}}>{inv.client}</span><span style={{fontFamily:'monospace',fontSize:11,color:T.muted}}>{inv.id}</span><SBadge status={inv.status}/>{inv.source==='gmail'&&<Pill color={T.blue}>Gmail</Pill>}</div><div style={{fontSize:12,color:T.s2,marginBottom:4}}>{inv.notes}</div><div style={{fontSize:11,color:T.muted,display:'flex',gap:12,flexWrap:'wrap'}}><span>{'Due: '}<span style={{color:inv.status==='Overdue'?T.red:T.silver}}>{inv.due}</span></span>{!['Paid','Cancelled'].includes(inv.status)&&<span style={{color:dleft(inv.due)<0?T.red:dleft(inv.due)<=7?T.gold:T.green,fontWeight:600}}>{dleft(inv.due)<0?Math.abs(dleft(inv.due))+'d overdue':dleft(inv.due)+'d remaining'}</span>}{inv.reminders>0&&<span style={{color:T.gold}}>{'◈ '+inv.reminders+' reminder'+(inv.reminders>1?'s':'')}</span>}</div></div><div style={{textAlign:'right',flexShrink:0}}><div style={{fontSize:22,fontWeight:800,color:T.s3,letterSpacing:-.5}}>{fmt(inv.amount)}</div><div style={{fontSize:11,color:T.muted,marginTop:3}}>{'Issued '+inv.issued}</div></div></div>{expanded===inv.id&&<div style={{marginTop:16,paddingTop:16,borderTop:'1px solid '+T.border,display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}><span style={{fontSize:11,color:T.muted,fontWeight:600}}>MOVE TO:</span>{STATUSES.filter(s=>s!==inv.status).map(s=><button key={s} onClick={e=>{e.stopPropagation();setInvoices(l=>l.map(i=>i.id===inv.id?{...i,status:s}:i));toast(inv.id+' → '+s,'s')}} style={{padding:'4px 12px',background:SC[s].bg,border:'1px solid '+SC[s].border,color:SC[s].text,fontSize:11,fontWeight:600,cursor:'pointer',borderRadius:20}}>{s}</button>)}<Btn v='g' style={{fontSize:11,padding:'5px 12px',marginLeft:'auto'}} onClick={e=>{e.stopPropagation();setInvoices(l=>l.map(i=>i.id===inv.id?{...i,reminders:i.reminders+1}:i));toast('Reminder: '+inv.id)}}>◈ Remind</Btn></div>}</div>)}{filt.length===0&&<div style={{textAlign:'center',padding:'48px 0',color:T.muted,fontSize:14}}>No invoices found</div>}</div></>}
      {subTab==='analytics'&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}><Card><div style={{fontSize:12,fontWeight:700,color:T.s2,letterSpacing:1,textTransform:'uppercase',marginBottom:16}}>Value by Status</div>{STATUSES.map(s=>{const v=invoices.filter(i=>i.status===s).reduce((a,b)=>a+b.amount,0);const mx=Math.max(...STATUSES.map(st=>invoices.filter(i=>i.status===st).reduce((a,b)=>a+b.amount,0)),1);return v>0?<div key={s} style={{marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12,marginBottom:6}}><span style={{color:SC[s].text,fontWeight:600}}>{s}</span><span style={{color:T.silver,fontWeight:700,fontFamily:'monospace'}}>{fmt(v)}</span></div><div style={{background:'rgba(255,255,255,.04)',height:6,borderRadius:3,overflow:'hidden'}}><div style={{height:'100%',background:SC[s].text,width:(v/mx*100)+'%',borderRadius:3}}/></div></div>:null})}</Card><Card><div style={{fontSize:12,fontWeight:700,color:T.s2,letterSpacing:1,textTransform:'uppercase',marginBottom:16}}>Aging Report</div><div style={{display:'flex',flexDirection:'column',gap:10}}>{[['Current',i=>dleft(i.due)>7,T.green],['Due Soon',i=>dleft(i.due)<=7&&dleft(i.due)>=0,T.gold],['1-30 Days',i=>dleft(i.due)<0&&dleft(i.due)>=-30,T.red],['30+ Days',i=>dleft(i.due)<-30,'#802020']].map(([label,fn,color])=>{const g=invoices.filter(i=>!['Paid','Cancelled'].includes(i.status)&&fn(i));return <div key={label} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'12px 14px',background:'rgba(255,255,255,.03)',borderRadius:10,border:'1px solid '+T.border}}><div style={{display:'flex',alignItems:'center',gap:10}}><div style={{width:8,height:8,borderRadius:'50%',background:color}}/><span style={{fontSize:13,color:T.silver}}>{label}</span></div><div style={{textAlign:'right'}}><div style={{fontSize:16,fontWeight:800,color}}>{g.length}</div><div style={{fontSize:11,color:T.s2,fontFamily:'monospace'}}>{fmt(g.reduce((a,i)=>a+i.amount,0))}</div></div></div>})}</div></Card></div>}
      {subTab==='agent'&&<GmailModal onClose={()=>setSubTab('list')} onAction={handleAct} invoices={invoices} inline/>}
    </div>
  </div>
}

function LeadsModule() {
  const [leads,setLeads]=useState([{id:1,name:'Ponce City Market',contact:'David Kim',phone:'404-555-2001',value:15000,status:'warm',notes:'Referred by Marcus Reid'},{id:2,name:'Emory University Campus',contact:'Sarah Chen',phone:'404-555-2002',value:22000,status:'hot',notes:'Looking to replace vendor Q2'},{id:3,name:'Atlanta Marriott Marquis',contact:'James Porter',phone:'404-555-2003',value:18500,status:'cold',notes:'Annual RFP in July'},{id:4,name:'Grady Memorial Hospital',contact:'Dr. Lisa Grant',phone:'404-555-2004',value:35000,status:'hot',notes:'Urgent security upgrade needed'}])
  const [form,setForm]=useState({name:'',contact:'',phone:'',value:'',notes:''}); const [ai,setAi]=useState(''); const [loading,setLoading]=useState(false); const [showAdd,setShowAdd]=useState(false)
  const sc={hot:T.red,warm:T.gold,cold:T.blue,closed:T.green}
  const pipeline=leads.filter(l=>l.status!=='closed').reduce((a,b)=>a+(b.value||0),0)
  const pitch=async l=>{setLoading(true);setAi('');const t=await aiCall('Write concise professional follow-up from Special Services Protection (Atlanta elite security firm) to '+l.contact+' at '+l.name+'. Context: '+l.notes+'. Value: $'+l.value+'/yr. Under 100 words.');setAi(t);setLoading(false)}
  const add=()=>{if(!form.name)return;setLeads(l=>[...l,{...form,id:Date.now(),status:'warm',value:parseFloat(form.value)||0}]);setForm({name:'',contact:'',phone:'',value:'',notes:''});setShowAdd(false)}
  return <div style={{flex:1,overflowY:'auto'}}>
    <TopBar title='Leads Agent' sub='Pipeline management & client outreach' actions={<><Pill color={T.gold}>{fmt(pipeline)+' Pipeline'}</Pill><Btn onClick={()=>setShowAdd(!showAdd)} style={{fontSize:12}}>+ Add Lead</Btn></>}/>
    <div style={{padding:'24px 32px',display:'flex',flexDirection:'column',gap:20}}>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12}}><StatCard label='Total Leads' value={leads.length} color={T.silver} icon='◎'/><StatCard label='Hot Leads' value={leads.filter(l=>l.status==='hot').length} color={T.red} icon='🔥'/><StatCard label='Pipeline' value={fmt(pipeline)} color={T.gold} icon='◈'/><StatCard label='Closed' value={leads.filter(l=>l.status==='closed').length} color={T.green} icon='✓'/></div>
      <AIBlock text={ai} label='AI Outreach Draft'/>
      {showAdd&&<Card><div style={{fontSize:13,fontWeight:700,color:T.silver,marginBottom:14}}>New Lead</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}><Inp val={form.name} onChange={v=>setForm(f=>({...f,name:v}))} ph='Business name' icon='◉'/><Inp val={form.contact} onChange={v=>setForm(f=>({...f,contact:v}))} ph='Contact name' icon='◈'/><Inp val={form.phone} onChange={v=>setForm(f=>({...f,phone:v}))} ph='Phone'/><Inp val={form.value} onChange={v=>setForm(f=>({...f,value:v}))} ph='Value/yr' type='number'/><Inp val={form.notes} onChange={v=>setForm(f=>({...f,notes:v}))} ph='Notes / referral'/><Btn onClick={add} style={{fontSize:12}}>+ Add Lead</Btn></div></Card>}
      <div style={{display:'flex',flexDirection:'column',gap:10}}>{leads.map(l=><div key={l.id} style={{background:T.card,border:'1px solid '+T.border,borderRadius:14,padding:'18px 22px',borderLeft:'3px solid '+(sc[l.status]||T.border)}}><div style={{display:'flex',justifyContent:'space-between',flexWrap:'wrap',gap:12,marginBottom:10}}><div><div style={{fontWeight:700,color:T.text,fontSize:15,marginBottom:3}}>{l.name}</div><div style={{fontSize:12,color:T.s2}}>{l.contact+(l.phone?' · '+l.phone:'')}</div></div><div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><span style={{fontWeight:800,color:T.s3,fontSize:16,fontFamily:'monospace'}}>{fmt(l.value)}<span style={{fontSize:11,fontWeight:400,color:T.s2}}>/yr</span></span><Pill color={sc[l.status]||T.silver}>{l.status}</Pill><Sel val={l.status} onChange={v=>setLeads(ls=>ls.map(x=>x.id===l.id?{...x,status:v}:x))} opts={['hot','warm','cold','closed'].map(s=>({v:s,l:s.charAt(0).toUpperCase()+s.slice(1)}))} style={{fontSize:12,padding:'5px 10px'}}/><Btn v='g' style={{fontSize:12,padding:'6px 14px'}} onClick={()=>pitch(l)} disabled={loading}>✦ Pitch</Btn></div></div>{l.notes&&<div style={{fontSize:12,color:T.s2,paddingTop:10,borderTop:'1px solid '+T.border}}>{l.notes}</div>}</div>)}</div>
    </div>
  </div>
}

function LinkedInModule() {
  const [topic,setTopic]=useState('new_contract'); const [detail,setDetail]=useState(''); const [tone,setTone]=useState('professional'); const [post,setPost]=useState(''); const [loading,setLoading]=useState(false); const [copied,setCopied]=useState(false)
  const generate=async()=>{setLoading(true);setPost('');const labels={new_contract:'New Contract Win',officer_spotlight:'Officer Spotlight',safety_tip:'Security Safety Tip',company_growth:'Company Growth',community:'Community Involvement'};const t=await aiCall('Write engaging LinkedIn post for Special Services Protection, premier Atlanta security firm. Topic: '+labels[topic]+(detail?'. Details: '+detail:'')+'.
Tone: '+tone+'. Include 3-5 hashtags. Under 220 words. Showcase SSP elite professionalism.');setPost(t);setLoading(false)}
  const copy=()=>{navigator.clipboard.writeText(post);setCopied(true);setTimeout(()=>setCopied(false),2000)}
  return <div style={{flex:1,overflowY:'auto'}}><TopBar title='LinkedIn Content' sub='AI-powered brand content generation'/><div style={{padding:'24px 32px',display:'flex',flexDirection:'column',gap:20}}><Card glow><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:16,marginBottom:16}}><div><label style={{fontSize:11,color:T.s2,fontWeight:600,letterSpacing:.5,textTransform:'uppercase',display:'block',marginBottom:8}}>Post Topic</label><Sel val={topic} onChange={setTopic} style={{width:'100%'}} opts={[{v:'new_contract',l:'New Contract Win'},{v:'officer_spotlight',l:'Officer Spotlight'},{v:'safety_tip',l:'Safety Tip'},{v:'company_growth',l:'Company Growth'},{v:'community',l:'Community'}]}/></div><div><label style={{fontSize:11,color:T.s2,fontWeight:600,letterSpacing:.5,textTransform:'uppercase',display:'block',marginBottom:8}}>Tone</label><Sel val={tone} onChange={setTone} style={{width:'100%'}} opts={[{v:'professional',l:'Professional'},{v:'bold',l:'Bold & Confident'},{v:'warm',l:'Warm & Community'}]}/></div></div><label style={{fontSize:11,color:T.s2,fontWeight:600,letterSpacing:.5,textTransform:'uppercase',display:'block',marginBottom:8}}>Additional Details</label><textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder='Names, locations, achievements...' style={{width:'100%',background:'rgba(255,255,255,.04)',border:'1px solid '+T.border2,borderRadius:10,padding:'10px 14px',color:T.text,fontSize:13,resize:'vertical',minHeight:80,outline:'none',fontFamily:'inherit',marginBottom:16}}/><Btn onClick={generate} disabled={loading} style={{fontSize:13,padding:'10px 24px'}}>{loading?'Crafting post...':'✦ Generate Post'}</Btn></Card>{post&&<Card><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><div><div style={{fontSize:14,fontWeight:700,color:T.text}}>Generated Post</div><div style={{fontSize:11,color:T.s2,marginTop:2}}>{post.length+' characters'}</div></div><div style={{display:'flex',gap:8}}><Btn v='g' style={{fontSize:12,padding:'7px 14px'}} onClick={copy}>{copied?'✓ Copied!':'Copy'}</Btn><Btn v='g' style={{fontSize:12,padding:'7px 14px'}} onClick={generate}>Regenerate</Btn></div></div><div style={{background:'rgba(255,255,255,.03)',borderRadius:10,padding:'18px 20px',border:'1px solid '+T.border}}><p style={{fontSize:14,color:T.s3,lineHeight:1.8,whiteSpace:'pre-wrap'}}>{post}</p></div></Card>}</div></div>
}

function PayrollModule() {
  const [payroll,setPayroll]=useState([{id:1,name:'Marcus Reid',role:'Senior Officer',hours:80,rate:22,status:'processed'},{id:2,name:'Tasha Williams',role:'Officer',hours:76,rate:18,status:'processed'},{id:3,name:'Devon Clark',role:'Officer',hours:72,rate:18,status:'pending'},{id:4,name:'Janet Moore',role:'Supervisor',hours:80,rate:26,status:'pending'},{id:5,name:'Ray Thompson',role:'Officer',hours:40,rate:18,status:'on-hold'}])
  const [ai,setAi]=useState(''); const [loading,setLoading]=useState(false)
  const gross=e=>e.hours*e.rate; const total=payroll.reduce((a,b)=>a+gross(b),0)
  const sc={processed:T.green,pending:T.gold,'on-hold':T.red}
  const summarize=async()=>{setLoading(true);setAi('');const t=await aiCall('Analyze payroll for Special Services Protection Atlanta (3-sentence exec summary, flag risks): '+payroll.map(e=>e.name+' ('+e.role+'): '+e.hours+'hrs @ $'+e.rate+'/hr = $'+gross(e)).join('; ')+'. Total: $'+total+'.');setAi(t);setLoading(false)}
  return <div style={{flex:1,overflowY:'auto'}}><TopBar title='Payroll' sub='Paychex integration & compensation management' actions={<Btn onClick={summarize} disabled={loading} style={{fontSize:12}}>{loading?'Analyzing...':'✦ AI Summary'}</Btn>}/><div style={{padding:'24px 32px',display:'flex',flexDirection:'column',gap:20}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12}}><StatCard label='Total Gross' value={fmt(total)} sub='This period' color={T.silver} icon='💰'/><StatCard label='Officers' value={payroll.length} color={T.blue} icon='◈'/><StatCard label='Pending' value={payroll.filter(p=>p.status==='pending').length} color={T.gold} icon='◌'/><StatCard label='Processed' value={payroll.filter(p=>p.status==='processed').length} color={T.green} icon='✓'/></div><AIBlock text={ai} label='AI Payroll Analysis'/><div style={{display:'flex',flexDirection:'column',gap:10}}>{payroll.map(e=><div key={e.id} style={{background:T.card,border:'1px solid '+T.border,borderRadius:14,padding:'18px 22px',display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:12}}><div style={{display:'flex',alignItems:'center',gap:14}}><div style={{width:42,height:42,borderRadius:12,background:'linear-gradient(135deg,#1a1a30,#2a2a50)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:13,fontWeight:700,color:T.s3}}>{e.name.split(' ').map(n=>n[0]).join('')}</div><div><div style={{fontWeight:700,color:T.text,fontSize:14}}>{e.name}</div><div style={{fontSize:12,color:T.s2}}>{e.role}</div></div></div><div style={{display:'flex',gap:12,alignItems:'center',flexWrap:'wrap'}}><div style={{textAlign:'right'}}><div style={{fontFamily:'monospace',fontSize:12,color:T.s2}}>{e.hours+'h @ $'+e.rate+'/h'}</div><div style={{fontSize:16,fontWeight:800,color:T.s3,letterSpacing:-.5}}>{fmt(gross(e))}</div></div><Pill color={sc[e.status]}>{e.status}</Pill>{e.status==='pending'&&<Btn v='success' style={{fontSize:12,padding:'6px 16px'}} onClick={()=>setPayroll(p=>p.map(x=>x.id===e.id?{...x,status:'processed'}:x))}>Approve</Btn>}</div></div>)}</div><Card style={{background:'linear-gradient(135deg,rgba(64,128,255,.06),rgba(64,128,255,.02))'}}><div style={{display:'flex',alignItems:'center',gap:14,marginBottom:14}}><div style={{width:40,height:40,borderRadius:10,background:'linear-gradient(135deg,#1040a0,#3060e0)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:16}}>🔗</div><div><div style={{fontWeight:700,color:T.text}}>Paychex Direct Sync</div><div style={{fontSize:12,color:T.s2}}>Auto-sync hours, rates & run payroll directly</div></div></div><Btn v='glass' onClick={()=>alert('Enter your Paychex API credentials in Settings.')} style={{fontSize:12}}>Connect Paychex Account</Btn></Card></div></div>
}

export default function App() {
  const [active,setActive]=useState('home')
  const alerts={invoices:1,leads:1,shifts:1}
  const render=()=>{switch(active){case 'home':return <HomeModule onNav={setActive}/>;case 'events':return <EventsModule/>;case 'shifts':return <ShiftsModule/>;case 'roster':return <RosterModule/>;case 'invoices':return <InvoiceModule/>;case 'leads':return <LeadsModule/>;case 'linkedin':return <LinkedInModule/>;case 'payroll':return <PayrollModule/>;default:return null}}
  return <div style={{display:'flex',minHeight:'100vh',background:T.bg}}><Sidebar active={active} setActive={setActive} alerts={alerts}/><div style={{flex:1,display:'flex',flexDirection:'column',overflow:'hidden',minWidth:0}}>{render()}</div></div>
}